// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDzjfSpKeAXDDWanHR9cr2zxxMsqwySK4',
    appId: '1:120324899900:web:c25faf334409397d21af39',
    messagingSenderId: '120324899900',
    projectId: 'sound-of-meme-5cd8e',
    authDomain: 'sound-of-meme-5cd8e.firebaseapp.com',
    storageBucket: 'sound-of-meme-5cd8e.appspot.com',
    measurementId: 'G-928D7KXV2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ui-7Vp1MZ2oXNEg2avq6HrOJok5rjto',
    appId: '1:120324899900:android:335d98101de5036b21af39',
    messagingSenderId: '120324899900',
    projectId: 'sound-of-meme-5cd8e',
    storageBucket: 'sound-of-meme-5cd8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTJdZtzw5whNjEzpxYBAAv-EIOaVFrUUA',
    appId: '1:120324899900:ios:6dae72fe1cfd533e21af39',
    messagingSenderId: '120324899900',
    projectId: 'sound-of-meme-5cd8e',
    storageBucket: 'sound-of-meme-5cd8e.appspot.com',
    iosBundleId: 'com.example.soundOfMeme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTJdZtzw5whNjEzpxYBAAv-EIOaVFrUUA',
    appId: '1:120324899900:ios:6dae72fe1cfd533e21af39',
    messagingSenderId: '120324899900',
    projectId: 'sound-of-meme-5cd8e',
    storageBucket: 'sound-of-meme-5cd8e.appspot.com',
    iosBundleId: 'com.example.soundOfMeme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDzjfSpKeAXDDWanHR9cr2zxxMsqwySK4',
    appId: '1:120324899900:web:450dbefba8cefda921af39',
    messagingSenderId: '120324899900',
    projectId: 'sound-of-meme-5cd8e',
    authDomain: 'sound-of-meme-5cd8e.firebaseapp.com',
    storageBucket: 'sound-of-meme-5cd8e.appspot.com',
    measurementId: 'G-3SWS36VVSX',
  );
}
